# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PatXuC4Ry3YILjab62B_U0bsLtoSvoGZ
"""



import matplotlib.pyplot as plt
import matplotlib.patches as patches
import random # Import for random ornament colors

# Create a figure and an axes object
fig, ax = plt.subplots(figsize=(8, 10))

# Define colors
red = '#D00000'    # Santa's suit, hat
white = '#FFFFFF'  # Beard, hat pompom, fur trim
skin = '#FFDBAC'   # Skin color
black = '#000000'  # Eyes
dark_blue = '#4169E1' # Royal Blue for the background

# Set limits and aspect ratio first, as they are used for background calculations
ax.set_xlim(-3, 3)
ax.set_ylim(-2.5, 3)
ax.set_aspect('equal')
ax.axis('off') # Hide the axes

# --- Background Rectangle (entire plot area) ---
# This rectangle will be the very back layer
background_rect = patches.Rectangle((ax.get_xlim()[0], ax.get_ylim()[0]),
                                    ax.get_xlim()[1] - ax.get_xlim()[0],
                                    ax.get_ylim()[1] - ax.get_ylim()[0],
                                    facecolor=dark_blue, edgecolor='none', zorder=0)
ax.add_patch(background_rect)

# --- Snow Rectangle ---
# This will be between the background and Santa, with a slightly higher zorder
snow_top_y = -1.5 # Adjust this value to set where the snow ends upwards
snow_height = abs(ax.get_ylim()[0] - snow_top_y)
snow_rect = patches.Rectangle((ax.get_xlim()[0], ax.get_ylim()[0]),
                              ax.get_xlim()[1] - ax.get_xlim()[0],
                              snow_height, facecolor=white, edgecolor='none', zorder=0.5)
ax.add_patch(snow_rect)

# --- Falling Snow (on the dark blue sky) ---
num_snowflakes = 100
for _ in range(num_snowflakes):
    # Random positions within the 'sky' area (above snow_top_y)
    sx = random.uniform(ax.get_xlim()[0], ax.get_xlim()[1])
    sy = random.uniform(snow_top_y, ax.get_ylim()[1]) # From top of snow to top of plot
    s_radius = random.uniform(0.02, 0.08) # Random size for snowflakes
    snowflake = patches.Circle((sx, sy), radius=s_radius, facecolor=white, edgecolor='none', zorder=1.5)
    ax.add_patch(snowflake)

# --- Body (chubby) ---
# The main body, a large red ellipse
body = patches.Ellipse((0, -0.5), width=2.0, height=2.5, angle=0,
                       facecolor=red, edgecolor='none', zorder=1)
ax.add_patch(body)

# --- Head ---
head = patches.Circle((0, 1.2), radius=0.6, facecolor=skin, edgecolor='none', zorder=2)
ax.add_patch(head)

# --- Beard ---
# A large white ellipse for the main part of the beard
beard_main = patches.Ellipse((0, 0.6), width=1.3, height=1.5, angle=0,
                             facecolor=white, edgecolor='none', zorder=3)
ax.add_patch(beard_main)

# Add some smaller white circles to give it a fluffy look
beard_left = patches.Circle((-0.5, 0.4), radius=0.4, facecolor=white, edgecolor='none', zorder=3)
ax.add_patch(beard_left)
beard_right = patches.Circle((0.5, 0.4), radius=0.4, facecolor=white, edgecolor='none', zorder=3)
ax.add_patch(beard_right)

# --- Hat ---
# Red cone/triangle for the main part of the hat
hat_cone = patches.Polygon([(-0.7, 1.5), (0.7, 1.5), (0, 2.5)],
                           facecolor=red, edgecolor='none', zorder=4)
ax.add_patch(hat_cone)

# White fur trim for the hat
hat_trim = patches.Ellipse((0, 1.5), width=1.6, height=0.4, angle=0,
                           facecolor=white, edgecolor='none', zorder=5)
ax.add_patch(hat_trim)

# White pompom for the hat
hat_pompom = patches.Circle((0, 2.6), radius=0.3, facecolor=white, edgecolor='none', zorder=6)
ax.add_patch(hat_pompom)

# --- Facial Features ---
# Eyes
left_eye = patches.Circle((-0.25, 1.4), radius=0.08, facecolor=black, edgecolor='none', zorder=7)
ax.add_patch(left_eye)
right_eye = patches.Circle((0.25, 1.4), radius=0.08, facecolor=black, edgecolor='none', zorder=7)
ax.add_patch(right_eye)

# Nose (small red circle)
nose = patches.Circle((0, 1.2), radius=0.15, facecolor=red, edgecolor='none', zorder=7)
ax.add_patch(nose)

# --- Arms ---
# Left arm (red rectangle/ellipse)
left_arm = patches.Ellipse((-1.0, 0.5), width=0.5, height=1.5, angle=45,
                           facecolor=red, edgecolor='none', zorder=1)
ax.add_patch(left_arm)

# Right arm (red rectangle/ellipse)
right_arm = patches.Ellipse((1.0, 0.5), width=0.5, height=1.5, angle=-45,
                            facecolor=red, edgecolor='none', zorder=1)
ax.add_patch(right_arm)

# --- Belt ---
belt = patches.Rectangle((-0.8, -0.6), 1.6, 0.3, facecolor='black', edgecolor='none', zorder=2)
ax.add_patch(belt)
buckle = patches.Rectangle((-0.15, -0.55), 0.3, 0.2, facecolor='gold', edgecolor='none', zorder=3)
ax.add_patch(buckle)

# --- Legs ---
# Left leg
left_leg = patches.Rectangle((-0.6, -2.0), 0.5, 1.0, facecolor=red, edgecolor='none', zorder=1)
ax.add_patch(left_leg)
# Right leg
right_leg = patches.Rectangle((0.1, -2.0), 0.5, 1.0, facecolor=red, edgecolor='none', zorder=1)
ax.add_patch(right_leg)

# --- Boots ---
# Left boot
left_boot = patches.Ellipse((-0.35, -2.0), width=0.8, height=0.5, angle=0,
                            facecolor='black', edgecolor='none', zorder=8)
ax.add_patch(left_boot)

# Right boot
right_boot = patches.Ellipse((0.35, -2.0), width=0.8, height=0.5, angle=0,
                             facecolor='black', edgecolor='none', zorder=8)
ax.add_patch(right_boot)


plt.title('Wesołych Świąt')
plt.show()